name: LMT Tangle
on:
  - push
  - pull_request

env:
  FILES: 'Implementation.md WhitespacePreservation.md SubdirectoryFiles.md LineNumbers.md IndentedBlocks.md'
  GOVER: '^1.16'

jobs:
  tangle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v27
        with:
        nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --command "go build"
        #nix develop --ignore-environment --keep MY_ENV_VAR --command echo $MY_ENV_VAR
      - name: Make sure main.go has not changed unintentionally
        run: |
          mv main.go main.go.orig
          ./lmt $FILES
          cmp -s main.go main.go.orig
